FROM python:latest


WORKDIR /app



# Install dependencies.
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt



# Copy code.
COPY ./ /app

CMD python3 -m unittest discover -v -s tests