name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: Dr-A-Soni/Dr-A-Soni-Readme@main
          CREDLY_USER: <Ami Soni_Credly> # optional, but default will use the same from github
